- name: 'Creating {{ flink_base_folder }}'
  file:
    path: '{{ flink_base_folder }}'
    state: directory

- name: 'Check local-action {{ playbook_dir }}/roles/common/files/flink-{{ flink_version }}-bin-scala_2.11.tgz'
  local_action: stat path={{ playbook_dir }}/roles//common/files/flink-{{ flink_version }}-bin-scala_2.11.tgz
  changed_when: false
  register: result_flink

- name: 'Copy local flink to {{ flink_base_folder }} '
  copy:
    src: 'flink-{{ flink_version }}-bin-scala_2.11.tgz'
    dest: '{{ flink_base_folder }}'
  when: result_flink.stat.exists

- name: 'Retrieve apache flink archive from {{ flink_url }} to {{ flink_base_folder }}'
  get_url:
    url: '{{ flink_url }}'
    dest: '{{ flink_base_folder }}'
    timeout: 600
  when: not result_flink.stat.exists

- name: 'Unarchive apache flink archive from {{ flink_final_folder }}-bin-scala_2.11.tgz to {{ flink_base_folder }}'
  unarchive:
    src: '{{ flink_final_folder }}-bin-scala_2.11.tgz'
    dest: '{{ flink_base_folder }}'
    owner: vagrant
    remote_src: yes

- name: 'Remove downloaded( {{ flink_final_folder }}-bin-scala_2.11.tgz) file'
  file:
    path: '{{ flink_final_folder }}-bin-scala_2.11.tgz'
    state: absent

- name: Set flink/bin as environment variable
  become: true
  template:
    src: flink.sh.j2
    dest: /etc/profile.d/flink.sh
    mode: 0644

- name: Reloading /etc/profile for activating Flink
  shell: . /etc/profile

- name: Copy flik-conf.yaml
  copy:
    src: flink-conf.yaml
    dest: '{{ flink_final_folder }}/conf/'

- name: Copy workers
  copy:
    src: workers
    dest: "{{ flink_final_folder }}/conf/"

- name: Copy masters
  copy:
    src: masters
    dest: "{{ flink_final_folder }}/conf/"