- name: 'Creating flink_usr_folder'
  file:
    path: "{{ flink_usr_folder }}"
    state: directory

- name: "Retrieve apache flink archive from {{ flink_url }} to {{ flink_usr_folder }}"
  get_url:
    url: "{{ flink_url }}"
    dest: "{{ flink_usr_folder }}"
    timeout: 600

- name: "Unarchive apache flink archive from {{ flink_usr_folder }}/flink-{{ flink_version }}-bin-scala_2.11.tgz to {{ flink_usr_folder }}"
  unarchive:
    src: "{{ flink_usr_folder }}/flink-{{flink_version }}-bin-scala_2.11.tgz"
    dest: "{{ flink_usr_folder }}"
    owner: vagrant
    remote_src: yes

- name: 'Remove downloaded( {{ flink_usr_folder }}/flink-{{flink_version }}-bin-scala_2.11.tgz ) file'
  file:
    path: '{{ flink_usr_folder }}/flink-{{flink_version }}-bin-scala_2.11.tgz'
    state: absent

- name: 'Set flink/bin as environment variable'
  template:
    src: flink.sh.j2
    dest: /etc/profile.d/flink.sh
    mode: 0644

- name: '[flink] Reload /etc/profile'
  shell: '. /etc/profile'

- name: Copy flik-conf.yaml
  copy:
    src: ../../../files/flink-conf.yaml
    dest: "{{ flink_usr_folder }}/flink-{{ flink_version }}/conf/"