---
- name: "Stop possible previous cluster"
  hosts: JobManager

  roles:
    - stop-cluster

- name: "[JobManager:TaskManagers] Provisioning nodes (JDK and Flink)"
  hosts: JobManager:TaskManagers
  become: true

  roles:
    - common