---
- name: Stop possible previous cluster
  hosts: JobManager

  roles:
    - stop-cluster

- name: Provisioning nodes with JDK and Flink
  hosts: JobManager:TaskManagers
  become: true

  roles:
    - common

- name: Provisioning JobManager with workers file and jobmanager.sh start
  hosts: JobManager

  roles:
    - jobmanager