- name: Provisioning nodes with JDK and Flink
  hosts: JobManager:TaskManagers
  become: true

  roles:
    - common

- name: Provisioning nodes with JDK and Flink
  hosts: JobManager

  roles:
    - start